language: python

python:
  - "2.7"
cache: pip

jdk:
  - oraclejdk7
  
install:
  - pip install -r requirements.txt
  - pip install pep8
  

matrix:
include:
  # Spark 1.5.2
  - jdk: openjdk7
    python: 2.7
    env: >
      TEST_SPARK_VERSION=1.5.2
      SPARK_HOME=`pwd`/thirdparty/spark-$TEST_SPARK_VERSION-bin-hadoop2.4
      PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
  # Spark 1.6.1
  - jdk: openjdk7
    python: 2.7
    env: >
      TEST_SPARK_VERSION=1.6.1
      SPARK_HOME=`pwd`/thirdparty/spark-$TEST_SPARK_VERSION-bin-hadoop2.4
      PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
      
before_script:
  # Download Spark
  - mkdir thirdparty
  - curl -O http://apache.mirror.cdnetworks.com/spark/spark-$TEST_SPARK_VERSION/spark-$TEST_SPARK_VERSION-bin-hadoop2.4.tgz
  - curl -O http://d3kbcqa49mib13.cloudfront.net/spark-2.0.1-bin-hadoop2.7.tgz
  - tar zxfC spark-2.0.1-bin-hadoop2.7.tgz thirdparty
  -

script:
  - pep8 --first `find pyexample -name "*.py"`
  - coverage run spark/y.py
